%BATCH_EXPORT_RMS_FIGURES  Script to make RMS figures
clc;
clearvars -except T

if exist('T','var')==0
   T = getfield(load('P:\Rat\BilateralReach\Solenoid Experiments\Solenoid-Table__5-ms-MM.mat','T'),'T');
end

% Create "channels" table with RMS response variable
C = tbl.stats.estimateChannelResponse(T,@(X){rms(X,1)},{'LFP'},'LFP');

% Estimate the time of maximum RMS; this appends other variables of
% interest to the table
C = tbl.addVarMaxMinTime(C,C.Solenoid_Onset*1e3,'LFP','tLFPmaxRMS','max');

% Get groupings for figures
[G,groupings] = findgroups(...
   C(:,{'SurgID',...
        'Area',...
        'Lamina',...
        'TrialType',...
        'Solenoid_Onset',...
        'ICMS_Onset'}));

% Solenoid: RFA
idx_C = (C.TrialType=="Solenoid") & ...
        (C.Area=="RFA") & ...
        (C.Solenoid_Onset==0.050);
idx_G = (groupings.TrialType=="Solenoid") &  ...
        (groupings.Area=="RFA") &  ...
        (groupings.Solenoid_Onset==0.050); 
utils.exportSaveFigure(C(idx_C,:),groupings(idx_G,:),...
   fullfile('figures/LFP-RMS/RFA-Solenoid'),...
   'PeaksAfter',50);

% ICMS: RFA
idx_C = (C.TrialType=="ICMS") & ...
        (C.Area=="RFA") & ...
        (C.ICMS_Onset==0);
idx_G = (groupings.TrialType=="ICMS") &  ...
        (groupings.Area=="RFA") &  ...
        (groupings.ICMS_Onset==0); 
utils.exportSaveFigure(C(idx_C,:),groupings(idx_G,:),...
   fullfile('figures/LFP-RMS/RFA-ICMS'),...
   'PeaksAfter',50);
     
% Solenoid + ICMS: RFA
idx_C = (C.TrialType=="Solenoid + ICMS") & ...
        (C.Area=="RFA") & ...
        (C.Solenoid_Onset==0.050) & ...
        (C.ICMS_Onset==0);
idx_G = (groupings.TrialType=="Solenoid + ICMS") &  ...
        (groupings.Area=="RFA") &  ...
        (groupings.Solenoid_Onset==0.050) & ...
        (groupings.ICMS_Onset==0); 
utils.exportSaveFigure(C(idx_C,:),groupings(idx_G,:),...
   fullfile('figures/LFP-RMS/RFA-SolenoidICMS'),...
   'PeaksAfter',50);

% Solenoid: S1
idx_C = (C.TrialType=="Solenoid") & ...
        (C.Area=="S1") & ...
        (C.Solenoid_Onset==0.050);
idx_G = (groupings.TrialType=="Solenoid") &  ...
        (groupings.Area=="S1") &  ...
        (groupings.Solenoid_Onset==0.050); 
utils.exportSaveFigure(C(idx_C,:),groupings(idx_G,:),...
   fullfile('figures/LFP-RMS/S1-Solenoid'),...
   'PeaksAfter',50);

% ICMS: S1
idx_C = (C.TrialType=="ICMS") & ...
        (C.Area=="S1") & ...
        (C.ICMS_Onset==0);
idx_G = (groupings.TrialType=="ICMS") &  ...
        (groupings.Area=="S1") &  ...
        (groupings.ICMS_Onset==0); 
utils.exportSaveFigure(C(idx_C,:),groupings(idx_G,:),...
   fullfile('figures/LFP-RMS/S1-ICMS'),...
   'PeaksAfter',50);
     
% Solenoid + ICMS: S1
idx_C = (C.TrialType=="Solenoid + ICMS") & ...
        (C.Area=="S1") & ...
        (C.Solenoid_Onset==0.050) & ...
        (C.ICMS_Onset==0);
idx_G = (groupings.TrialType=="Solenoid + ICMS") &  ...
        (groupings.Area=="S1") &  ...
        (groupings.Solenoid_Onset==0.050) & ...
        (groupings.ICMS_Onset==0); 
utils.exportSaveFigure(C(idx_C,:),groupings(idx_G,:),...
   fullfile('figures/LFP-RMS/S1-SolenoidICMS'),...
   'PeaksAfter',50);
