function jointFig = makeJointInputDistributionScatter(C)
%MAKEJOINTINPUTDISTRIBUTIONSCATTER Make joint scatter of input where x-axis is peak times and y-axis is peak spike rates
%
%  jointFig = tbl.gfx.makeJointInputDistributionScatter(C);
%
% Inputs
%  C - Table from `new_analysis.m`
% 
% Output
%  jointFig - Figure handle
%
% See also: Contents

jointFig = figure('Name','Distribution of Peak Times','Units','Normalized',...
   'Position',[0.132, 0.157, 0.5, 0.6],...
   'PaperOrientation','landscape','Color','w');

colormap(jointFig,'copper');

% Make Solenoid panel
ax = subplot(2,1,1);
set(ax,'Parent',jointFig,'NextPlot','add','XColor','k','YColor','k','FontName','Arial','YLim',[0 8]);
idx = string(C.Type)~="ICMS";
nCol = size(C.peakTime,2);
swarmchart(ax,...
   (C(idx,:).peakTime(:)- repmat(C.Solenoid_Onset__Exp(idx),nCol,1))*1000,...
   log(C(idx,:).peakVal(:)),getSizeData(C(idx,:).sortRank(:)),repmat(C(idx,:).Depth,nCol,1),'filled',...
   'MarkerFaceAlpha',0.5,'MarkerEdgeAlpha',0.5,...
   'XJitter','randn','XJitterWidth',7.5,'YJitter','density');
% xlabel(ax,'Peak Time (ms)','Color','k','FontName','Arial',...
%    'FontName','Arial','FontSize',20);
ylabel(ax,'log(spikes/sec)','Color','k','FontName','Arial',...
   'FontName','Arial','FontSize',20);
text(ax,-50,0.5,'Solenoid',...
   'FontName','Arial','Color','k','FontSize',20,'FontWeight','bold',...
   'HorizontalAlignment','center','VerticalAlignment','bottom');

% Make ICMS panel
ax = subplot(2,1,2);
set(ax,'Parent',jointFig,'NextPlot','add','XColor','k',...
   'YColor','k','FontName','Arial','XAxisLocation','top','YDir','reverse','YLim',[0 8]);
idx = string(C.Type)~="Solenoid";
swarmchart(ax,...
   (C(idx,:).peakTime(:)- repmat(C(idx,:).ICMS_Onset__Exp,nCol,1))*1000,...
   log(C(idx,:).peakVal(:)),getSizeData(C(idx,:).sortRank(:)),repmat(C(idx,:).Depth,nCol,1),'filled',...
   'MarkerFaceAlpha',0.5,'MarkerEdgeAlpha',0.5,...
   'XJitter','randn','XJitterWidth',7.5,'YJitter','density');
xlabel(ax,'Peak Time (ms)','Color','k','FontName','Arial',...
   'FontName','Arial','FontSize',20);
ylabel(ax,'log(spikes/sec)','Color','k','FontName','Arial',...
   'FontName','Arial','FontSize',20);
text(ax,-50,0.5,'ICMS',...
   'FontName','Arial','Color','k','FontSize',20,'FontWeight','bold',...
   'HorizontalAlignment','center','VerticalAlignment','top');
cb = colorbar(ax,'Location','south','AxisLocation','out','LineWidth',2,'FontSize',16);
set(cb.Label,'String','Depth (\mum)','FontName','Arial');

   function sz = getSizeData(pkRank)
      MAP = [72, 36, 24, 18, 14, 10, 8, 7, 6];
      sz = MAP(pkRank);
   end
end