%BATCH_EXPORT_RMS_FIGURES  Script to make RMS figures
clc;
clearvars -except T

if exist('T','var')==0
%    T = getfield(load('P:\Rat\BilateralReach\Solenoid Experiments\Solenoid-Table__5-ms-MM.mat','T'),'T');
   T = getfield(load('Solenoid-Table_5-ms_excluded_ipsi.mat','T'),'T');
end

% Create "channels" table with RMS response variable
C = tbl.stats.estimateChannelResponse(T,@(X){rms(X,1)},{'LFP'},'LFP');

% Estimate the time of maximum RMS; this appends other variables of
% interest to the table
C = tbl.addVarMaxMinTime(C,C.Solenoid_Onset*1e3,'LFP','tLFPmaxRMS','max');

%% Get groupings and run through ad-hoc figure combination definitions
% % Get groupings for figures
% [G,groupings] = findgroups(...
%    C(:,{'SurgID',...
%         'Area',...
%         'Lamina',...
%         'TrialType',...
%         'Solenoid_Onset',...
%         'Solenoid_Offset',...
%         'ICMS_Onset'}));
% 
% % Solenoid: RFA
% idx_C = (C.TrialType=="Solenoid") & ...
%         (C.Area=="RFA") & ...
%         (C.Solenoid_Onset==0.050) & ...
%         (C.Solenoid_Offset==0.100) & ...
%         (C.ICMS_Onset==inf);
% idx_G = (groupings.TrialType=="Solenoid") &  ...
%         (groupings.Area=="RFA") &  ...
%         (groupings.Solenoid_Onset==0.050) & ...
%         (groupings.Solenoid_Offset==0.100) & ...
%         (groupings.ICMS_Onset==inf);
% utils.exportSaveFigure(C,groupings(idx_G,:),...
%    fullfile('figures/LFP-RMS/RFA-Solenoid'),...
%    'PC_Type',"Solenoid",...
%    'PeaksAfter',50);
% 
% % ICMS: RFA
% idx_C = (C.TrialType=="ICMS") & ...
%         (C.Area=="RFA") & ...
%         (C.ICMS_Onset==0) & ...
%         (C.Solenoid_Offset==inf) & ...
%         (C.Solenoid_Onset==inf);
% idx_G = (groupings.TrialType=="ICMS") &  ...
%         (groupings.Area=="RFA") &  ...
%         (groupings.ICMS_Onset==0) & ...
%         (groupings.Solenoid_Offset==inf) & ...
%         (groupings.Solenoid_Onset==inf); 
% utils.exportSaveFigure(C,groupings(idx_G,:),...
%    fullfile('figures/LFP-RMS/RFA-ICMS'),...
%    'PC_Type',"Solenoid",...
%    'PeaksAfter',0);
%      
% % Solenoid + ICMS: RFA
% idx_C = (C.TrialType=="Solenoid + ICMS") & ...
%         (C.Area=="RFA") & ...
%         (C.Solenoid_Onset==0.050) & ...
%         (C.ICMS_Onset==0) & ...
%         (C.Solenoid_Offset==0.100);
% idx_G = (groupings.TrialType=="Solenoid + ICMS") &  ...
%         (groupings.Area=="RFA") &  ...
%         (groupings.Solenoid_Onset==0.050) & ...
%         (groupings.ICMS_Onset==0) & ...
%         (groupings.Solenoid_Offset==0.100); 
% utils.exportSaveFigure(C,groupings(idx_G,:),...
%    fullfile('figures/LFP-RMS/RFA-SolenoidICMS'),...
%    'PC_Type',"Solenoid",...
%    'PeaksAfter',50);
% 
% % Solenoid: S1
% idx_C = (C.TrialType=="Solenoid") & ...
%         (C.Area=="S1") & ...
%         (C.Solenoid_Onset==0.050) & ...
%         (C.Solenoid_Offset==0.100) & ...
%         (C.ICMS_Onset==inf);
% idx_G = (groupings.TrialType=="Solenoid") &  ...
%         (groupings.Area=="S1") &  ...
%         (groupings.Solenoid_Onset==0.050) & ...
%         (groupings.Solenoid_Offset==0.100) & ...
%         (groupings.ICMS_Onset==inf); 
% utils.exportSaveFigure(C,groupings(idx_G,:),...
%    fullfile('figures/LFP-RMS/S1-Solenoid'),...
%    'PC_Type',"Solenoid",...
%    'PeaksAfter',50);
% 
% % ICMS: S1
% idx_C = (C.TrialType=="ICMS") & ...
%         (C.Area=="S1") & ...
%         (C.ICMS_Onset==0) & ...
%         (C.Solenoid_Offset==inf) & ...
%         (C.Solenoid_Onset==inf);
% idx_G = (groupings.TrialType=="ICMS") &  ...
%         (groupings.Area=="S1") &  ...
%         (groupings.ICMS_Onset==0) & ...
%         (groupings.Solenoid_Offset==inf) & ...
%         (groupings.Solenoid_Onset==inf); 
% utils.exportSaveFigure(C,groupings(idx_G,:),...
%    fullfile('figures/LFP-RMS/S1-ICMS'),...
%    'PC_Type',"Solenoid",...
%    'PeaksAfter',0);
%      
% % Solenoid + ICMS: S1
% idx_C = (C.TrialType=="Solenoid + ICMS") & ...
%         (C.Area=="S1") & ...
%         (C.Solenoid_Onset==0.050) & ...
%         (C.ICMS_Onset==0) & ...
%         (C.Solenoid_Offset==0.100);
% idx_G = (groupings.TrialType=="Solenoid + ICMS") &  ...
%         (groupings.Area=="S1") &  ...
%         (groupings.Solenoid_Onset==0.050) & ...
%         (groupings.ICMS_Onset==0) & ...
%         (groupings.Solenoid_Offset==0.100);  
% utils.exportSaveFigure(C,groupings(idx_G,:),...
%    fullfile('figures/LFP-RMS/S1-SolenoidICMS'),...
%    'PC_Type',"Solenoid",...
%    'PeaksAfter',50);
