% FIGURES  Figures generated by Matlab code in +Figures package goes here for local saves
% MATLAB Version 9.2 (R2017a) 01-Sep-2020
%
% Note: all graphics file types are added to .gitignore to avoid repository
%       needlessly expanding in size. So this should be initially empty
%       when the repository is cloned (aside from this Contents file).