function fig = plotPETH(T,surgID,blockIndex,trialType,channelName,varargin)
%PLOTPETH Plot peri-event spike histograms in plot that is laid out by channel
%
%  fig = analyze.rat.plotPETH(T,surgID,blockIndex,trialType);
%  fig = analyze.rat.plotPETH(T,surgID,blockIndex,trialType,channelName);
%
% Inputs
%  T - Main data table
%  surgID - e.g. 'R19-227'
%  blockIndex - Scalar (usually starts at zero)
%  trialType - 1: Solenoid (only) 2: ICMS (only) 3: Solenoid+ICMS
%  channelName - (Optional) char array - if specified, returns only that
%                       channel
%  
% Output
%  fig - Figure handle with plots laid out for channels by depth

if nargin > 4
   fig = tbl.gfx.PETH(T,...
         {'SurgID',surgID,... % "filtArgs"
          'BlockIndex',blockIndex,...
          'ChannelID',channelName,...
          'Type',trialType},...
       'AxesParams', ... % (Optional 'Name', value args)
         {'NextPlot','add',...
          'XColor','k',...
          'YColor','k',...
          'LineWidth',1.25,...
          'ColorOrder',cfg.gfx('ColorOrder'),...
       'XLim',[-100 200]},varargin{:});
else
   fig = tbl.gfx.PETH(T,...
         {'SurgID',surgID,... % "filtArgs"
          'BlockIndex',blockIndex,...
          'ChannelID','A002',...
          'Type',trialType},...
       'AxesParams', ... % (Optional 'Name', value args)
         {'NextPlot','add',...
          'XColor','k',...
          'YColor','k',...
          'LineWidth',1.25,...
          'ColorOrder',cfg.gfx('ColorOrder'),...
       'XLim',[-100 200]},varargin{:});
end

end


