function fig = plotPEP(T,surgID,blockIndex,trialType,channelName,varargin)
%PLOTPEP Plot peri-event potentials in plot that is laid out by channel
%
%  fig = analyze.rat.plotPEP(T,surgID,blockIndex,trialType);
%  fig = analyze.rat.plotPEP(T,surgID,blockIndex,trialType,channelName);
%
% Inputs
%  T      - Main data table
%  surgID - e.g. 'R19-227'
%  blockIndex - Scalar (usually starts at zero)
%  trialType - 1: Solenoid (only) 2: ICMS (only) 3: Solenoid+ICMS
%  channelName - (Optional) char array - if specified, returns only that
%                       channel
%  
% Output
%  fig - Figure handle with plots laid out for channels by depth

% Make LFP event-related potential (peri-event potential; PEP)
if nargin > 4
      fig = tbl.gfx.PEP(T,...
         {'SurgID',surgID,... % "filtArgs"
          'BlockIndex',blockIndex,...
          'ChannelID',channelName,...
          'Type',trialType},...
       'AxesParams',...
         {'NextPlot','add',...
          'XColor','k',...
          'YColor','k',...
          'LineWidth',1.25,...
          'ColorOrder',cfg.gfx('ColorOrder'),...
          'XLim',[-100 200],...
          'YLim',[-2000 1000]},varargin{:});
else
   fig = tbl.gfx.PEP(T,...
         {'SurgID',surgID,... % "filtArgs"
          'BlockIndex',blockIndex,...
          'ChannelID','A002',...
          'Type',trialType},...
       'AxesParams',...
         {'NextPlot','add',...
          'XColor','k',...
          'YColor','k',...
          'LineWidth',1.25,...
          'ColorOrder',cfg.gfx('ColorOrder'),...
          'XLim',[-100 200],...
          'YLim',[-2000 1000]},varargin{:});
end

end